name: rescrit
description: "A search and rescue robot"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
   sdk: '^3.5.0'


dependencies:
  flutter:
    sdk: flutter
  
  camera: ^0.11.0+2
  cupertino_icons: ^1.0.6
  animated_splash_screen: ^1.3.0
  pytorch_lite: ^4.3.0
  flutter_pytorch: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons
    - assets/models/model_classification.pt
    - assets/labels/label_classification_imageNet.txt
    - assets/models/yolov5s.torchscript
    - assets/labels/labels_objectDetection_Coco.txt

